name: Pipeline

on:
  push:
    branches: [ develop ]
env:
  APPLICATION_NAME: startupapp

jobs:
  build_image_push_to_ECR:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # see: https://github.com/aws-actions/configure-aws-credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ASIATIPIZMXSTZPDQGO7
        aws-secret-access-key: 4YuUyFuoO4nvLnb1X50g2CkicV5OGtLwI/sd3WMV
        aws-session-token : IQoJb3JpZ2luX2VjEAMaCXVzLWVhc3QtMSJGMEQCIAqzY1QRsHmglVUyB44JkRQ1wHIA9Y3YeTwA7jeTZHJWAiBI0QQt42DdtePlWOZpzN7sLloNFX0mzZfV15zW1EGcyyqpAwh7EAAaDDIyNDM2MzM3NDA1MyIM8aAla1HydTG6maIKKoYDt+ucxZ08LqN+Xv9wBDktFdlvWWCw/K+8TfHCnvcslAsqBVHLQjMqlR2yFZ1j+Wiv3iDf3647n4y7UOKfgigiysku1cXTDamS8os0PPAl/MZxM3MZvbbZ+UiLPYoplV8fVFgGsSoLVpBoS0DfYJwhNro65iiocufxqOUoAkqSDepDejq00LwQ+Q2uGXl2dsBK15kgWdDaPyH2GXNGONRBnL+ye/VyeU629ar4pXNB2i714QZBeAIWtOt0Ye0hRdkrvG8ZW4Y+BWGkxnDds3EsU9ks8rqNwb/J1NMqonqk8cwXvwRZhlEMgpJXsinvFZNo0v8P/Dz/pPsOY4jhgn9unNvGLHg5vENYbmKJxiyC9ZUggjNq1eSSA+WRsjyYDQ40VIfTbM8zcZGcx36gOtbeXTm89tAEyN/+VG3H4bGohKNiVhnUpXYAm3WNhbkUZxhohsoavsav1YYdBB4aDeC8uLxBAkSTT6eD/086cm/W5+AzSJHIHLP2J7+Tmbem7Ul2KasS3ypWMPKMj5gGOqcBVyrZgV5F9snfI16fu0l9+4g11BTKHUGDzGALJ38/BI2viZznioGUjlW/AME/gZnnRZCjadk/CL52V0wQGfC/w4w1lBonyqaL/RrFM24nnWVI5tcpsYqCGoCj0B6o883vbXSkPMXDh2acBG3F4//pG2RMDZ0Fu86q8B0DqbAXMmwNYMOh/zrPgq3sf0/eErg8jwEPGKzjSkbDvuiLr63T05IqRXS3bYM=
        aws-region: us-east-1

    # see: https://github.com/aws-actions/amazon-ecr-login
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: 224363374053.dkr.ecr.us-east-1.amazonaws.com
        ECR_REPOSITORY: aws-sagemaker-mlops-tcb
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
  submit_training_job:
    needs: [build_image_push_to_ECR]
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
    - uses: actions/checkout@v2
    - name: Fire SageMaker
      id: sm_train
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ASIATIPIZMXSTZPDQGO7
        AWS_SECRET_ACCESS_KEY: 4YuUyFuoO4nvLnb1X50g2CkicV5OGtLwI/sd3WMV
        AWS_DEFAULT_REGION: us-east-1
        BUCKET_NAME: tcb-bankcd
        PREFIX: xgb/train/
        IAM_ROLE_NAME: arn:aws:iam::224363374053:role/service-role/AmazonSageMakerServiceCatalogProductsUseRole
        GITHUB_SHA: ${{ github.sha }}
      run: |
        pip install --no-cache-dir --upgrade awscli pandas boto3 sagemaker requests fsspec s3fs tabulate
        python training-job.py
        cat details.txt >> report.md
        cml-send-comment report.md
